[package]
name = "seibyou_hayare"
version = "0.1.0"
authors = ["kgtkr <kgtkr.jp@gmail.com>"]
edition = "2018"

[dependencies]
egg-mode = "0.12.0"
tokio-core = "0.1"
futures = "0.1.14"
toml = "0.4"
serde="*"
serde_derive="*"
failure="*"